### ISSUE TITLE
[Feature] More robust connection handling

### ISSUE THREAD

**Issue by csrftoken** [tortoise/tortoise-orm#117]
![image](https://user-images.githubusercontent.com/29940756/54982394-b720dc80-4fe5-11e9-88ee-f0e3ecefb9e7.png)

I have a problem like this, but I don't know why.
Can you help me?
Thanks.

**Comment by grigi** [comment]
I'm not sure what is going on there? Was this service up and running a while?

**Comment by abondar** [comment]
@csrftoken Could you please provide some more info please?
I think following info would be particularly interesting:
- How long query was executing? How long does it execute if you request it directly from DB?
- Is there any other errors in log?
- What is timeout for your request?

**Comment by grigi** [comment]
At my work we got a new manual tester, and she is fantastic, and wanted us to test all kinds of environmental issues like bizarre timeouts and disconnects, etc… 
So I thought that one thing we don't do yet is handle connection errors/failures of various kinds.
We should try and have various sensible defaults for it where we can.

Things we had to handle:
1. The DB closes connections on you.
2. Your connection stalls because a router forgot the IP flow.

These were things we did to ensure it was reliable:
1. Cycle the connections to the DB every `~30m`
2. Do a liveness check (literally a `SELECT 1`), and if we don't get the right result within `~2s` we assume connection is dead, and recycle it.
3. Cache the liveness check for `~5s` so we don't unnecessarily delay the system. (reduces impact of point 2)

We should add something like this to Tortoise as a standard "sane' configuration.

**Comment by csrftoken** [comment]
@grigi I think you are right。
When a single database connection is made, If more than a certain time when the break，this database connection may be bad.
But I don't have a relevant use case，Wait until I get a more useful context。

**Comment by csrftoken** [comment]
I used this orm in the production environment. Our website has not done any promotion yet. I think the framework is very good and the author is very nice.
If there is an opportunity, I would like to participate in the code contribution in this framework.

**Comment by grigi** [comment]
Thanks for the offer @csrftoken 
There is many things to do, listed at #19 → Look at the "TODO — Easy" section.
I'm thinking since you have some experience now with `sanic` maybe you can start by either doing an integration guide with sanic, or a light plugin.

In the mean time I'll leave this as a feature request, for more robust connection handling.

**Comment by csrftoken** [comment]
Write a sanic plugin to integrate this orm?

**Comment by grigi** [comment]
Sure why not? Start with an example, then expand it to make setup & teardown clean, and add a lightweight plugin to the `tortoise/contrib/` folder (and then add it to the docs).

OR

Anything else you want to do. Other things we probably need is awareness :smile:

**Comment by csrftoken** [comment]
ok

**Comment by grigi** [comment]
@csrftoken please try release v0.11.9 it has an auto reconnect for MySQL

**Comment by csrftoken** [comment]
ok，I have a question. Can a single connection hold? Is connection pooling a better solution?

**Comment by grigi** [comment]
In terms of reliability, no, there should be no benefit going pooled,
In terms of performance, yes, it should have better throughput under load.
Consider the current implementation as a connection pool of exactly one. We don't re-create connections all the time.

The issue holding pools off is that the context behaves differently in Py3.7, and we get a different context as to what we expect. This is most obvious when one holds a transaction, and then the scope inside the with statement loses context, and uses a different connection, so the transaction fails.

As to why contextvars in Py3.7 behaves the way it does, I'm not sure. It seems as if the context-manager we use for transaction management changes the context, so the aenter and aexit gets different contexts.

**Comment by csrftoken** [comment]
yep, I think the framework has become more stable. 
In my company, We use Py3.6.8.
We don't think Py3.7 is stable enough and support for third-party libraries.
