### ISSUE TITLE
Provide concrete examples of what tortoise improves on

### ISSUE THREAD

**Issue by xsduan** [tortoise/tortoise-orm#131]
So I stumbled upon this library and it seems interesting, though from an end user looking at usage I really don't see the difference between this and async-on-top ORMs, other than just taking the readme's word for it.

I don't know if it would go over my head, but it would be nice to have an example provided of an instance where tortoise could potentially be faster, more responsive, etc on async over, let's say, peewee-async, which has a very similar API.

**Comment by grigi** [comment]
Hi Shane

Good points, a lot of what was written in the readme was very relevant when this project started, but has become less relevant over the last year. Back then there was no ORMs that met the basic flexibility requirement of being able to change DBs and with an async interface that wasn't absolutely terrible.
I know of at least one good alternative now.

The real benefit, I suppose is higher concurrency over less DB connections, which is unfortunately a crapshoot as we have an unsolved context related issue. (see `new_pool` and `concurrent` branches)

For benchmarks, I did some at https://github.com/tortoise/orm-benchmarks#results-sqlite which was mostly so that we could find performance bottlenecks and fix them. It only puts us as second fastest in that set of ORMS, losing to Pony ORM (which is a very nice ORM, imho). It was also the only async orm that met the criteria at that time, but I should add any other working options I can find.

Performance has not been a huge criteria until we feel we are complete enough. (which we aim for v1.0).
Also I have not set up the benchmark to use MySQL/PostgreSQL yet, as it was mostly to find bottlenecks, of which the current known ones that can be improved are:
* `Model.__init__`
* `Queryset.resolve_filters`
* converting fields to DB types

**Comment by grigi** [comment]
Have made several documentaion updates, hopefully it is more clear now
