### ISSUE TITLE
Datetime field bug

### ISSUE THREAD

**Issue by m1step** [tortoise/tortoise-orm#144]
Datetime fields are not created on call Tortoise.generate_schemas()

My model: ![image](https://user-images.githubusercontent.com/25801200/59934038-4e65c680-9453-11e9-9ffe-330fb7de2bf5.png)

My DB schema after call generate_schemas(): ![image](https://user-images.githubusercontent.com/25801200/59934127-81a85580-9453-11e9-8336-16f8994e5c9a.png)

Drivers i used: MySQL, PostgreSQL

The second bug is datetimefields are unable to save.

Insert operation: http://joxi.ru/p270b7pHKjxpnA
Debug log: http://joxi.ru/82QbO5JiwqdK5A

**Comment by grigi** [comment]
Thank you for reporting the bug, and with so much detail.

One thing I have noticed is that for `date` and `created_at` fields you type-annotated them, instead of assigned them (as in replace the `:` with a `=`).

Please change class `Log` to assign the date/created_at fields and see if that resolves your issue?

**Comment by m1step** [comment]
Ohhhhh, sorry. my bad. i think, i need more rest :D
