### ISSUE TITLE
can you create a example for fastapi？

### ISSUE THREAD

**Issue by sylvoslee** [tortoise/tortoise-orm#188]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by grigi** [comment]
As I see it FastAPI is basically starlette with Pydantic for serialisation, and then some extra spice.
So a prerequisite to make the integration seamless, we need Pydantic serialisation support.

Wow, this can get quite big, it would end up to be a DRF-like framework when all is done, which would be awesome.

**Comment by grigi** [comment]
I used GraphQL from an consumer POV, and the thing that got me was how to make partial matches performant? Because the API I used didn't speed up if I requested a small portion. So obviously it was not very "smart" about it.

I have never used Graphene either. Still I'm more interested in Pydantic at this stage. I wonder if one could map Graphene over Pydantic? (for an initial naïve implementation)
It's always easier to work on optimizations after you have working repeatable benchmarks. And since the GraphQL interface is well defined, we can do anything we want as long as the tests pass.

I did a talk about my experiences in optimization once. Where the first step after setting up a a benchmark suite and profiling the data was to remove nearly all the "obvious optimizations" as they actually made it slower…

Please report back with your experiences re building a GraphQL interface using this proposed stack?

**Comment by leandrob13** [comment]
I tested it in FastAPI and it was as straight forward as shown in the docs:

```python
def create_app(r: APIRouter) -> FastAPI:
    app = FastAPI()
    app.include_router(r)
    register_tortoise(
        app, db_url=DATABASE_URL, modules={"models": ["app.db.postgres.models"]}, generate_schemas=True
    )
    return app
```

Probably what needs to be specified is that FastAPI is in fact a Starlette app and it can be initialized the same way.

**Comment by grigi** [comment]
Yes, we can do that.
Also, we now have pydantic serialisation support, so we could also build an example that provides a more complete fastapi experience.
