### ISSUE TITLE
How to get related model from a ForeignKeyField?

### ISSUE THREAD

**Issue by mojimi** [tortoise/tortoise-orm#205]
I couldn't find any way to achieve this since when you access a ForeignKeyField property from a model class it just returns a property object.

The following is an example of what I'm trying to achieve :

```python
from tortoise import fields, Model

class Base(Model):

  @classmethod
  async def new(cls, **kwargs):
    create_params = {}
    for key, value in kwargs.items():
      if key in cls._meta.fields:
        create_params[key] = value
      elif key.endswith('_id'):
        key = key.replace('_id', '')
        if key in cls._meta.fields:
          model = getattr(cls, key).model #This method doesn't exist
          create_params[key] = model(id=value)

    return await cls.create(create_params)

class Book(Base):
  title = fields.CharField(100)

class Page(Base):
  book = fields.ForeignKeyField(Book, related_name='pages')
  content = fields.TextField()

#...

#The context here is a view that has book_id in the url parameters
#There's no need to query the database for said book beforehand
page = await Page.new(content='Hello World', book_id=1)
```

How can I achieve this?

Bonus points for being able to know if it's a forward or reverse relationship (single value or list)

**Comment by grigi** [comment]
I'm not understanding why you have the new method?

e.g. with the following models:
```py
class Book(Model):
  title = fields.CharField(100)

class Page(Model):
  book = fields.ForeignKeyField(Book, related_name='pages')
  page = fields.IntField()
  content = fields.TextField()
```

You can create a page like so:
```py
page = await Page.create(content='Hello World', page=2, book_id=1)
```
You can get all pages like so (ordered):
```py
# Assume book exists
pages = await book.pages.order_by('page'))
```
To get a pages's book, you do this:
```py
# Assume page exists
await page.fetch_related('book')
book = page.book
```
The `fetch_related` is needed because `book` needs to be fetched, and until it is you only access the FK property.
The better syntax is to just do `book = await page.book` but that somehow didn't get implemented yet.

Also, look at the tests here: https://github.com/tortoise/tortoise-orm/blob/develop/tests/fields/test_fk.py

**Comment by mojimi** [comment]
@grigi Sorry I wasn't clear enough.

I'm trying to create a "smarter" creation method that automatically maps a `field_id` parameter to a instance if `field` is a relationship field on the table.

So, both `Page.new(content='Hello World', book_id=1)` and `Page.new(content='Hello World', book_id=book)` would work.

But in order for that to work I need to be able to fetch the class from the ForeignKeyField.

My suggestion is that the `_meta` class should return the actual `Field` instead of a property

**Comment by grigi** [comment]
I don't understand, why would you need to check if a field is a FK? Didn't you define it in your own models?

**Comment by mojimi** [comment]
> 
> 
> I don't understand, why would you need to check if a field is a FK? Didn't you define it in your own models?

I did but this is for the base class, it's supposed to be a common method that adapts to all models

**Comment by grigi** [comment]
Would this interface be adequate: https://tortoise-orm.readthedocs.io/en/latest/setup.html#tortoise.Tortoise.describe_model ?
You'd call `Tortoise.describe_model(self)` to get this data.

Note that I'm busy changing this for the v0.14 release, and is considering changing the API. I want the self-description to be used by the DDL generation, etc...

So please tell me how you would want to use it, or how I should extend it so that it works for you?

**Comment by mojimi** [comment]
@grigi thank you, the describe_model is enough, wasn't aware of it
