### ISSUE TITLE
cyclic fk references even without fks

### ISSUE THREAD

**Issue by AEnterprise** [tortoise/tortoise-orm#213]
**Describe the bug**
generate_scheme is failing, claiming cyclic fk references even with all foreign keys commented out

**To Reproduce**
1) use following models: https://gist.github.com/AEnterprise/3256c81c0eb2adb4b4dcd1018e04e559
2) initialize tortoise (i was using mysql database in case that matters)
3) try to generate schemes
4) comment out all foreign keys
5) try to generate again

**Expected behavior**
at step 3 it should generate schemes as there is no cyclic dependency. but even if there was then it should work at step 5 without any foreign keys in play but doesn't either

**Comment by grigi** [comment]
Thanks for the bugreport. I'll have a proper look tonight, I see you have been setting `collation="utf8mb4_general_ci"` which is not supported at this stage. That appears to be the MySQL specific case-insensitive collation format? (Right now it won't do anything).

How would you envision a db-generic case-insensitive field to look like? The issue with specifying collations, is that they are entierly DB-specific. That's fine, we can support DB-specific overrides, but case-insensitive behaviour is a common request, so we should support it as a first tier feature.

Do you want a parameter on the field, e.g. `CharField(max_length=10, case_insensitive=True)` or some other way. see #155 for a discussion as to the complexities to support this.
Also, since I'm busy with #206 I could add CI support in?

**Comment by AEnterprise** [comment]
oh that is leftover from using another orm in the past. This isn't fully case insensitive from what i know, it still has casing when storing things in the database but this hints to the database that when using queries it should do them case insensitive (so a converting function isn't needed to force upper or lower casing)

the more important bit to me is that it's utf8mb4 because i need to be able to the full unicode range including emojis, while these collocations are also database dependant they are imo as important as case insensitivity for usecases where you need to support specific charsets

some extra flags for it might be nice though my main issue atm is that generate schemes keeps messing up my database so i need to use my own sql script to get everything to behave

**Comment by grigi** [comment]
We default to `utf8mb4` for MySQL for that same reason. MySQL's default for encoding is bizarre.
https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/backends/base/config_generator.py#L49

the collation is a charset for the index. So any indexes over a `_ci` collation will be always be done in a normalised case. So index lookups becomes case insensitive. And I think they emulate the same rules for table scans (but uncertain).

Yes, the actual row has the full-case data.

**Comment by grigi** [comment]
I had a look, and I think I know what the issue is.
Your InfractionMigration model has a Meta defining the table name as "infraction".
You then have a Infraction model that has no specified table name, but it also defaults to "infraction"

So the error message is actually incorrect. What it should say is "conflict in table names…"

**Comment by AEnterprise** [comment]
oh i did the model that way because i actually am migrating the table as well, as you see the scheme is slightly different, using proper fields for timestamps, is there another/better way to do that or should this be in a separate migration script instead?

thanks for the info, didn't know tortoise defaulted to that, peewee def didn't so that's where that came from

and finally i'm running into some other weird things with scheme generation, not sure if all of them are intended or not, should i just open a new issue about those?

**Comment by grigi** [comment]
I'm happy for you to amend this issue with more details or create more issues. It would probably make sense to put things that are related in a single issue.

One of my goals of 0.14 (next release) is to refactor fields so that we have a simpler-to-expand field definition, and then to use that data to generate schemas better.

So this is a good time to direct the conversation to where it will be useful for you.

**Comment by grigi** [comment]
> oh i did the model that way because i actually am migrating the table as well, as you see the scheme is slightly different, using proper fields for timestamps, is there another/better way to do that or should this be in a separate migration script instead?

Right now we don't support schema migrations in any way, so it may just be better to manage your own schema for more complicated long-lived projects?

**Comment by AEnterprise** [comment]
the problem with this application is that data migration is needed. the timestamp field currently is an integer, i wana move that to the better suited timestamp field so this involves loading in the data, storing it in memory, asking the user to make the needed database changes (as i don't really see a good way of running sql direclty with tortoise to make the change), and then updating all those rows again with the date (as the converstion to cause them all to reset to jan 1 1970)

but guess i'll just split these off away from the main models into a separate file to load in the migration script
