### ISSUE TITLE
[sqlite] order_by doesn't work correctly with DecimalField and sqlite backend

### ISSUE THREAD

**Issue by bbedward** [tortoise/tortoise-orm#256]
**Describe the bug**
The sqlite backend's schema generator generates `DecimalField` as a `VARCHAR(40)`

When you do an `order_by` with tortoise using a `DecimalField`, it orders it as if it's a `varchar` field instead of a numeric field.

**To Reproduce**
```
# Test model
class Test(Model):
    decimal = fields.DecimalField(max_digits=10, decimal_places=2)

# Insert some records
await Test(
    decimal=0
).save()

await Test(
    decimal=27.27
).save()

await Test(
    decimal=9.99
).save()

# Query with order_by
await Test.all().order_by('decimal')
```

Results come back in the order:

```
0
27.27
9.99
```

**Expected behavior**
Results come back in the correct order:

```
0
9.99
27.27
```

**Additional context**
Looks to be only an issue with the sqlite backend, as it uses `varchar` to represent `DecimalField`

**Comment by grigi** [comment]
Yes, SQLite doesn't support decimal types.

So it is a game of compromises.

The options I had was to either lose accuracy (meaning 0.2 would become 0.2000000000000000001) or to store as strings.

I'll see if there is a way to fix the sorting/aggregations via a collation, as I'd rather keep numerical accuracy.
But if not changing to `FLOAT` and doing quantization would at least constrain the numerical loss?
Would functions/aggregations would now return a float instead of a decimal?

**Comment by bbedward** [comment]
I like storing them as strings for the loss of precision issue, but perhaps order by could just cast - because I think the floating point precision loss is better than sorting as if it was a string.

`order by (cast decimal as decimal)`, e.g

**Comment by grigi** [comment]
I think this will be a good litmus test for #206
Let me see if I can get sorting and aggregates to work as expected.

**Comment by grigi** [comment]
Just an update on progress:

I had a look if we could solve some of this with COLLATION, but alas SQLite supports only 3 text-focused collations by standard.

Then what would happen if we store decimals as REAL, and then quantize for accuracy. This is an option, but it only solves the ordering issue, but introduces accuracy issues everywhere. This is what every other ORM I looked at does, but I always disliked how my Decimal objects become floats almost randomly depending on back-end, and consider it a bad solution.

Seeking a better solution instead, found that `ORDER BY CAST(<col> AS NUMERIC)` works, I feel it is a better soluton.
Doing AVG/SUM on decimal fields as string will auto-convert to type `NUMERIC` but MIN/MAX will then compare strings and be susceptible to same bad ordering issues.

`select max(CAST(a AS NUMERIC)) from a;` Does the right thing by the looks of it.

My plan of action:
* [x] Added tests for sorting & aggregations
* [x] MySQL/PostgreSQL passes
* [ ] add `CAST(<column> AS NUMERIC)` to SQLite order-by
* [ ] add `CAST(<column> AS NUMERIC)` to SQLite aggregate functions
* [ ] Do regular `to_python_value` operations on aggregate columns, so that we end up with Decimals instead of either REALs or TEXTs. (or some other kind of weirdness)

This should be a best-case emulation achievable with SQLite, I think. Not perfect accuracy, but much closer than having all Decimals transparently become floats later on.

**Comment by grigi** [comment]
v0.15.5 is release with the fixes for this. Please test

**Comment by bbedward** [comment]
Awesome, thank you!

**Comment by bbedward** [comment]
@grigi  Yes, it works as expected now.

Thank you

**Comment by grigi** [comment]
Added some SQLite caveats to docs
