### ISSUE TITLE
allow overriding autogenerated values

### ISSUE THREAD

**Issue by AEnterprise** [tortoise/tortoise-orm#263]
**Is your feature request related to a problem? Please describe.**
Currently if you pass a value for a field that gets set automatically (because generated=True on an intfield for example) that gets ignored completely.
However in some cases you don't want the database to set this value at all but use something you provide.
An example would be a data migration, or other script that needs to read data from logs or other databases and merge them into a single table

**Describe the solution you'd like**
Being able to overwrite this behavior in specific instances to perform data migrations or other operations where the id must generated by the database in 99.99% of the cases but in a few cases is set from user input

**Describe alternatives you've considered**
Using a secondary model that is basically a duplicate of the existing one but with generated set to false. however since this points to the same table it confuses the scheme generator and crashes. to be able to load this model a seperate database connection would be required for just this one model

**Comment by grigi** [comment]
:thinking:

Currently what happens is:
1. You have a model with a generated PK.
2. You pass in a pk value via the constructor
3. The model is marked as not being persisted in the db by default
4. You save it, it then doesn't even look at the pk value, but reads it from the DB and sets it.

To make this work I can think of a two options:
1. The constructor tests if you passed in a valid value for the PK, and if you have then sends it along with the INSERT statement. 
2. You pass in a pk, and a special variable to state that you are overriding the PK

Even though 1 is more "magical", 2 feels werid to me.

The real issue is that the prepared SQL statement doesn't have a PK in the INSERT statement. So if you want it to be both generated and not, we will have to prepare two different ones, and this will require plumbing.

The other "big" issue is that we don't want this to be the norm, because then the ownership of data becomes blurred, and it isn't a pattern we want to encourage.

The last issue is with bulk inserts. There we need the data to be uniform. And how do we decide? I feel it will have to be explicit in that case.

So, after thinking about it the plan is:
1a. If a generated PK is set, and the model is not db-linked, use the fallback insert. We need a performant way to detect this.
1b: A special variable will be set on constructor, so we assume that a valid generated PK has been set, and use the fallback insert.
2. Fallback prepared statement should be done in cases of a generated pk. Generated return value should be ignored for this state.
3. For bulk inserts we should be able to set the method up-front, as the point of bulk inserts is to minimise overheads.

Do you prefer 1a or 1b?

**Comment by AEnterprise** [comment]
i don't think 1 is as magical, i see it as more of a "generate it unless told otherwise" thing. it's indeed not something to promote as it's pointless in most cases. but when doing data transformation, cleanup or migration it is sometimes required to have full control over the assigned IDs for some items

i think 1a might be more user friendly?

for bulk inserts i'd say it makes sense to require them all to be the same (so all with autogenerated or manually specified PK)

**Comment by grigi** [comment]
Released v0.15.6 with ability to override a generated pk transparently. Please test :-)

**Comment by AEnterprise** [comment]
working great, thanks a lot!
