### ISSUE TITLE
Support auto generate UUID for non pk field

### ISSUE THREAD

**Issue by lntuition** [tortoise/tortoise-orm#279]
First, Thank you for support nice software :)
I find that UUIDField only auto generate UUID4 only that field is primary key.
How about support auto generate UUID key for non pk field?

Maybe we can use like below
``` Python
uid = fields.UUIDField(auto_generate=True) # default : False
```

Also, I'm not good at orm and database well. I want to hear about other's opinions.
I really appreciate if anyone answer to me! Thank you :+1:

**Comment by abondar** [comment]
Hi!

Actually, for pk uuid fields generation is done inside of Tortoise just like that:
```
    def __init__(self, **kwargs) -> None:
        if kwargs.get("pk", False):
            if "default" not in kwargs:
                kwargs["default"] = uuid4
        super().__init__(**kwargs)
```

So, if you wanna same behaviour for non-pk uuid field you just have to do it like that:
```
from uuid import uuid4

uid = fields.UUIDField(default=uuid4)
```

**Comment by lntuition** [comment]
@abondar Thank you for your friendly comment :)

What do you think about adding new keywords to `UUIDField` for auto-generate UUID for non pk field? Adding new keyword can be useful to user and also prevent unnecessary uuid import.   

If you do not agree, then how about add some example code about this issue?
I think it is hard to find upper solution just looking document. 
We must view source code to solve upper problem.

Thank u and Have a nice day ! :smile:

**Comment by abondar** [comment]
Well, I think there really is issue with `default` parameter for fields documentation. It can accept functions as value and this function will be called if field has to be populated by default value.

It isn't documented in field's reference in docs, which, I think, happened mostly because it's behaviour emulates Django's same parameter, so it hasn't bothered us before. 
I think we will have to improve docs in this terms.

Regarding `auto-generate` parameter I would oppose such solution, because it's seems to be too specific and would bring more confusion to users, than be really helpful, cause people will have to find out what exactly this params mean and it means we would have to document it thoroughly.

But if we gonna document something I think we should better document `default` param behaviour :)

**Comment by grigi** [comment]
Yes, I have been having to do many support queries where the docs either had something missing, or was hard to find. We need doc guidelines.

**Comment by lntuition** [comment]
> Well, I think there really is issue with `default` parameter for fields documentation. 

I agree with above opinion. So i will close this issue after documentation updated. Thank u :)

**Comment by grigi** [comment]
Documented default and all standard field params better: https://tortoise-orm.readthedocs.io/en/latest/fields.html#module-tortoise.fields.base

**Comment by s3dm** [comment]
Hi, `tortoise.exceptions.ConfigurationError: Field 'agt_pk' (UUIDField) can't be DB-generated` is thrown when 

```python
class Agent(Parent):
    agt_pk = fields.UUIDField(pk=True, generated=True)
```
Successfully installed tortoise-orm-0.16.21
