### ISSUE TITLE
Support foreign key to unique field

### ISSUE THREAD

**Issue by lntuition** [tortoise/tortoise-orm#281]
Well, I tried to set fk with other unique key. But i cannot find method with tortoise-orm.
Does tortoise support like below option? I cannot find with document.

With Django orm, it can be represented by `to_field` param.
> ForeignKey.to_field
>
> The field on the related object that the relation is to. By default, Django uses the primary key of the related object. If you reference a different field, that field must have unique=True.

**Comment by grigi** [comment]
Oh, you mean to non-primary key, but still unique, key?

No, we just have FK's to the primary key of a table at this stage.

Technically it should work, not sure how much work it will be to actually make it work.

**Comment by lntuition** [comment]
> Oh, you mean to non-primary key, but still unique, key?

@grigi Yeah, that's what i mean. I hope tortoise will support this feature soon. Thank you for comment.

**Comment by lntuition** [comment]
https://github.com/tortoise/tortoise-orm/blob/c28784ce25f4adfe1b634092940dc82cb9b7b55e/tortoise/backends/base/schema_generator.py#L174-L193

@grigi I think foreign key schema reference field name is hardcoded with
` field=field_object.reference.model_class._meta.db_pk_field `
I don't know much about internal of tortoise-orm. Just change field name with passed param to ForeignKeyField can break other side?

**Comment by grigi** [comment]
Yes, you are right. I suspect there are many small hardcoded code for this. There was a naïve assumption after all :-)

I think the ForeignKeyInstance should contain the remote db field as a parameter, and we set it in the constructor, and only validate it on init() (as at the time of defining the FK we may not have the remote model class yet). 

Then to verify it works everywhere, add it to the generated schema so we can test it's DDL generation is correct, add it to some of the test models, and copy the fk test cases, and also test for fails.

So this will be quite a lot of work. Do you want to start on it?

**Comment by lntuition** [comment]
thank you for comment :) Also i want to contribute with this issue, but i'm not sure that i can do this... Because i'm beginner with this domain...

If there are someone who can lead me from begining, i will try to anaylaze internal of tortoise-orm..

**Comment by grigi** [comment]
Sure, if you have time I can help you :+1: 

You already started, the `db_pk_field` is a `str` that contains the DB column name that we are joined to.

Lets start by only adding it to FK, as O2O is implemented almost identically, and will be easy to get working later on.

I'd start by adding a parameter like `to_field: Optional[str] = None` to [`def ForeignKeyField(...)` ](https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/fields/relational.py#L392-L397) then propagate it up to the instance constructor.

I would not validate anything in the Field, as we likely don't have the remote models loaded yet.
[`_init_relations`](https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/__init__.py#L270) is where relationships are resolved and validated.

I'd then add logic in the `fk_fields` block to set the `to_field` to default value (e.g. `...model_class._meta.db_pk_field`) it it is `None` or first validate that field exists, and is uniquely indexed.
It would make sense, I think, to use the class field name, and then translate it to the DB name, and save that. That way the user won't have to guess if the column name got changed for reasons of consistency or character set?

Then use the new variable when generating SQL instead of the `model_class._meta.db_pk_field`.
I'd recommend writing a small example and setting logging to DEBUG eg:
```py
import logging
logging.basicConfig(level=logging.DEBUG)
```
so that you can see what is emitted, and get that fixed up so your example works.

At this point I'd want to review it and we should add some tests, etc...

**Comment by lntuition** [comment]
@grigi thank you for your support. I make [PR](https://github.com/tortoise/tortoise-orm/pull/287) with WIP. I think that i check well generating schema logic. But i'm not sure. Can you help me at this point? If you think that it is worked well, i will make example and TC soon. (Or maybe i can make TC without checking, but i also want to get some review that my code is going in a good direction) 

Thank you and have a nice day :smile:
