### ISSUE TITLE
Tortoise forces the PK field to be Int

### ISSUE THREAD

**Issue by Midorina** [tortoise/tortoise-orm#334]
**Describe the bug**
TortoiseORM changes the field of PK column to `IntField` and automatically increments it no matter if a value is set or not. (Reason of this is found in the first comment)

**To Reproduce**
```python
class Test(Model):  
    guild_id = fields.BigIntField(pk=True)      
    message_id = fields.BigIntField()
```
```python
await Test.create(guild_id=123456789, message_id=123456789)
```

**Expected behavior**
A new table with 2 big integer columns (guild_id is PK)
and a new row with 123456789 values on both of its columns.

**What actually happens**
A new table with an integer auto-incrementing column (guild_id [PK]) and a big integer column (message_id)
and a new row with the value 1 in its `guild_id` column (message_id is fine.) [Reason of this is found in the first comment]

**Additional context**
I see that Tortoise forces the PK column to be an integer and auto-incrementing (Reason for this is found in the first comment). Is this on purpose or a bug?

**Comment by Midorina** [comment]
https://tortoise-orm.readthedocs.io/en/latest/models.html

> If this is used on an Integer Field, generated will be set to True unless you explicitly pass generated=False as well. If generated is True any value you parse for this field is silently ignored and it will let the database assign a value instead.

Although I think this should be False as default, this note explains the situation.
However, it still changes the type of the column from BigInt to Int.

**Comment by grigi** [comment]
> https://tortoise-orm.readthedocs.io/en/latest/models.html
> 
> > If this is used on an Integer Field, generated will be set to True unless you explicitly pass generated=False as well. If generated is True any value you parse for this field is silently ignored and it will let the database assign a value instead.
> 
> Although I think this should be False as default, this note explains the situation.
> However, it still changes the type of the column from BigInt to Int.

I'm pretty sure that blurp is old, and not entirely correct anymore. You can pass a value to the pk without `generated=False` being set since 0.15.6.
I've removed the outdated portion of the docs.

Ok, so I had a look and I can't replicate your issue of assigning a value that gets clobbered.

However, if you look at the schema generated for SQLite, it only supports auto-increment on `INTEGER` (but type is not important for SQLite, so it doesn't really matter). If you try anything else you'll get `AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY`.

On MySQL we use `BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT` and PostgreSQL we use `BIGSERIAL NOT NULL PRIMARY KEY` (yes every DB is different).

To demonstrate (SQLite):
```py
class Test(Model):
    guild_id = fields.BigIntField(pk=True)
    message_id = fields.BigIntField()

await Test.create(guild_id=123456789, message_id=123456789)
```
generates:
```sql
CREATE TABLE IF NOT EXISTS "test" (
    "guild_id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "message_id" BIGINT NOT NULL
);
INSERT INTO "test" ("guild_id","message_id") VALUES (?,?): [123456789, 123456789]
```

and:
```py
class Test(Model):
    guild_id = fields.BigIntField(pk=True, generated=False)
    message_id = fields.BigIntField()

await Test.create(guild_id=123456789, message_id=123456789)
```
generates:
```sql
CREATE TABLE IF NOT EXISTS "test" (
    "guild_id" BIGINT NOT NULL  PRIMARY KEY,
    "message_id" BIGINT NOT NULL
);
INSERT INTO "test" ("guild_id","message_id") VALUES (?,?): [123456789, 123456789]
```

And both look correct for SQLite, which is what I'm assuming you are using because you didn't specify and it has the quirk you are explaining.

**Comment by Midorina** [comment]
Ok. Apparently my tortoise-orm was outdated (it was version 0.13, while the newest version on pip is 0.16.2) and after updating it, tortoise no longer forces the pk to be an int using postgres. Sorry for not making sure that I use the latest version before creating the issue, and thank you.
