### ISSUE TITLE
exclude parameter does't work in pydantic_model_creator

### ISSUE THREAD

**Issue by eugenyProchan** [tortoise/tortoise-orm#342]
Hello! Huge shanks for the library!
I discovered that parameter exclude does't work, or i used it wrong.
Fields which i pass to this, does't exclude from result.

This is how i use it
`filtered_model = MyModel.filter(name='example')`
`pydantic_model  = pydantic_model_creator(MyModel, exclude=('account'))`
`for_serialize  = pydantic_model.from_tortoise_orm(filtered_mode)`

but i getting excluded field 'account' in for_serialize.json()

tortoise-orm 0.16.1
pydantic 1.4

**Comment by grigi** [comment]
Hi, thanks you :-)

Looking at your example:
```py
pydantic_model = pydantic_model_creator(MyModel, exclude=('account'))
```
I noticed you just wrapped the 'account' in brackets `()`.
Python has a syntax quirk in that `()` without a comma is a context bracket, and with a comma is a tuple. So either put a comma in `('account',)` or use square brackets for a list `['account']` as there is no such grammatical ambiguity with those.

Also, a string is iterable, meaning `list('account')` becomes `['a', 'c', 'c', 'o', 'u', 'n', 't']`
 so it likely tried to exclude those instead of what you wanted.

**Comment by eugenyProchan** [comment]
Thank you! I have tryed your solution, that works perfectly!
