### ISSUE TITLE
in postgresql generate_schemas but hit 

### ISSUE THREAD

**Issue by mengyyy** [tortoise/tortoise-orm#407]
**Describe the bug**
I use postgresql and i found i could not connect to database.
And i found i did not use `Tortoise.generate_schemas` after `Tortoise.init` 
so i add `await Tortoise.generate_schemas()` after `Tortoise.init`
But i get this error

```
File /usr/local/lib/python3.8/dist-packages/tortoise/backends/asyncpg/__init__.py, line 1, in <module>
    from .client import AsyncpgDBClient
File /usr/local/lib/python3.8/dist-packages/tortoise/backends/asyncpg/client.py, line 10, in <module>
    from tortoise.backends.asyncpg.schema_generator import AsyncpgSchemaGenerator
File /usr/local/lib/python3.8/dist-packages/tortoise/backends/asyncpg/schema_generator.py, line 3, in <module>
    from pymysql.converters import encoders

ModuleNotFoundError: No module named 'pymysql'
```

**To Reproduce**
```python
await Tortoise.init(
    {
        "connections": {"default": {"engine": "tortoise.backends.asyncpg", "credentials": self.credentials}},
        "apps": {"models": {"models": [self.models], "default_connection": "default"}},
    },
     _create_db=False,
)
await Tortoise.generate_schemas()
```

**Expected behavior**
connect successfully

**Additional context**
After i install `pymysql` everything work
But when i update `tortoise-orm` pip do not install `pymysql` 

Python3.8
Ubuntu 18.04 x64

**Comment by lntuition** [comment]
@mengyyy Thank you for your reporting! 
@grigi from 72f84f0 and 95c384a lead this one.

Using pymysql with other db driver looks weird. Because `aiomysql` use `pymysql` internal but other didn't. I think we need to removing that logic to other db driver. Or do we need to make our escaper? 

Also, I think we check all db drivers at once with CI(using testall) lead this. I think we need to seperate CI with each drivers. What do you think? At a minimum just test seperately with one version(maybe 3.7 or 3.8) looks good.

**Comment by long2ice** [comment]
Yeah,that's mine,because I can't find some escaper like pymysql in other driver,now current solution is just install pymysql even though you don's use it, before we do some other actions.

**Comment by long2ice** [comment]
And I will fix later.
