### ISSUE TITLE
No changes persist unless inside a transaction

### ISSUE THREAD

**Issue by grigi** [tortoise/tortoise-orm#49]
**Describe the bug**
* My simple benchmark applet https://github.com/tortoise/orm-benchmarks/blob/master/src/tortoise/test_a.py does not actually persist/insert unless the .create() is wrapped inside a transaction.

**Expected behavior**
It should autocommit. https://docs.djangoproject.com/en/2.1/topics/db/transactions/#autocommit-details

**Comment by Zeliboba5** [comment]
Is it problem only for sqlite or postgres and mysql as well? In my projects I haven't encountered it with postgres.

If it's sqlite only, than may be it is because sqlite3 module in python have autocommit off by default (https://docs.python.org/3/library/sqlite3.html#sqlite3-controlling-transactions), so behaviour is leaked to aiosqlite.

If it is indeed just sqlite it should be fixed with specifying `isolation_level = None` for sqlite connection.

**Comment by grigi** [comment]
Good point, I only tested it on sqlite so far.
Let me test a bit more.

**Comment by grigi** [comment]
Ok, it appears to be the case. I'll add the fix to #47
