### ISSUE TITLE
Allow to know whether a field is required

### ISSUE THREAD

**Issue by florimondmanca** [tortoise/tortoise-orm#88]
**Is your feature request related to a problem? Please describe.**
At the moment, there is no way to know whether a field is required (e.g. cannot left empty when creating a model instance) on a `Model`.

**Describe the solution you'd like**
Alter the behavior of `default`: if not provided to the `Field`'s constructor, it should be set to a sentinel value, e.g. `DEFAULT_NOT_PROVIDED`. Then, we can have `required` (or `blank`, to follow the Django API?) be a property computed as `return self.default is not DEFAULT_NOT_PROVIDED`.

The API would look like this:

```python
from tortoise.models import Model
from tortoise import fields

class BlogPost(Model):
    title = fields.CharField(max_length=100)
    description = fields.TextField(default=None, null=True)

assert BlogPost._meta.fields_map["title"].blank
assert not BlogPost._meta.fields_map["description"].blank
```

**Describe alternatives you've considered**
Add a `blank` parameter to `Field`'s `__init__()` and simply store it on the field. However, we don't have any validation mechanism for now so we wouldn't be able to act upon `blank` which may be counter-intuitive. I suppose for now it's better to compute it from whether a `default` was passed.

**Additional context**
I'm playing around with building Django REST Framework-like serialization on top of Tortoise, with Pydantic as a validation backend. My approach is to dynamically build a Pydantic model out of a Tortoise `Model`. Pydantic has built-in validation for required/non-required fields, so knowing whether a field is required is a blocker for now.

Also — I am willing to work on this issue. 😄  I'd be glad to have pointers at where I should be careful when altering the behavior of `default` (e.g. assigning to a sentinel value), although from what I've seen it should be quite easy to figure out.

**Comment by grigi** [comment]
Yes, I think we can safely auto-generate the "required" attribute from a combination of the `null` and `default` parameters.

In Django the "blank" parameter is only really used by auto-form generation and is otherwise ignored. It is one of the areas where persistence rules and presentation rules is mixed, which is not ideal, as it implies inter-dependency. So lets see if we can leave it out.

Also, have a look at #13 & #39 which is both features we wanted to get to post 1.0, but as you are showing interest :-)

Also #14 which led to a more standardised init, it also makes models cleaner to discover. So If there is anything you feel is needed, we could extend that interface to provide.
I'd prefer something explicit, and not an implementation detail, so we have the capability of changing internals without breaking it for everyone.

**Comment by florimondmanca** [comment]
> In Django the "blank" parameter is only really used by auto-form generation and is otherwise ignored.

FYI, I believe the Django REST Framework does use `blank` to figure out whether a field is required (which makes sense because a REST `POST` request is a form too, in a way).

But it always seemed strange to me that we needed to specify `blank=True` even though a default was passed, hence the proposal which we seem to agree upon. :-)

> I'd prefer something explicit, and not an implementation detail, so we have the capability of changing internals without breaking it for everyone.

I'm not sure what you mean exactly by this?

Also, I've taken a look at those issues you mentioned and will keep them under my radar. :-)

**Comment by grigi** [comment]
I meant that we should instead of letting the user use what is currently an internal interface, instead formalise it, so that we can at worst know exactly what we need to keep compatible for, in case of internal change.

E.g. we need to support deprecation period, so if we need to change something incompatibily internally, we can still have a stable interface for this, so that we annoy our users less.
A good read on this topic (and many others) is: https://emptysqua.re/blog/api-evolution-the-right-way/
